export const historyActions = {
    GET_HISTORY_BY_ORG: 'GET_HISTORY_BY_ORG',
    GET_HISTORY_BY_ORG_SUCCESS: 'GET_HISTORY_BY_ORG_SUCCESS',
    GET_HISTORY_BY_ORG_ERROR: 'GET_HISTORY_BY_ORG_ERROR',
    GET_ONE_HISTORY: 'GET_ONE_HISTORY',
    GET_ONE_HISTORY_SUCCESS: 'GET_ONE_HISTORY_SUCCESS',
    GET_ONE_HISTORY_ERROR: 'GET_ONE_HISTORY_ERROR',
    UPDATE_HISTORY: 'UPDATE_HISTORY',
    UPDATE_HISTORY_SUCCESS: 'UPDATE_HISTORY_SUCCESS',
    UPDATE_HISTORY_ERROR: 'UPDATE_HISTORY_ERROR',
}