export const orgActions = {
    GET_ORG_BY_OWNER: 'GET_ORG_BY_OWNER',
    GET_ORG_BY_OWNER_SUCCESS: 'GET_ORG_BY_OWNER_SUCCESS',
    GET_ORG_BY_OWNER_ERROR: 'GET_ORG_BY_OWNER_ERROR',
    CREATE_ORG: 'CREATE_ORG',
    CREATE_ORG_SUCCESS: 'CREATE_ORG_SUCCESS',
    CREATE_ORG_ERROR: 'CREATE_ORG_ERROR',
    UPDATE_ORG: 'UPDATE_ORG',
    UPDATE_ORG_SUCCESS: 'UPDATE_ORG_SUCCESS',
    UPDATE_ORG_ERROR: 'UPDATE_ORG_ERROR',
    UPDATE_ORG_LOGO: 'UPDATE_ORG_LOGO',
    UPDATE_ORG_LOGO_SUCCESS: 'UPDATE_ORG_LOGO_SUCCESS',
    UPDATE_ORG_LOGO_ERROR: 'UPDATE_ORG_LOGO_ERROR',
    CLEAR_CURRENT: 'CLEAR_CURRENT',
    CLEAR_ERROR: 'CLEAR_ERROR',
    CLEAR_STATE: 'CLEAR_STATE'
}